### ISSUE TITLE
Erstellen der autobahn.txt mit realen Einträgen

### ISSUE THREAD

**Issue by DieAkuteSense** [Abuturku/Navi#10]

**Comment by DieAkuteSense** [comment]
Wer will das machen? :D

**Comment by AdniLunA** [comment]
die von mir erfüllt ja eigl die anforderungen, oder nicht? er hatte ja zu beginn gesagt, dass es nciht nötig ist, dass wir ein existierendes netz vorweisen.

wenn ihr aber drauf besteht, könnte ich das auch tun...

**Comment by DieAkuteSense** [comment]
Ist gut so, jedoch wäre es dann gut eine Skizze als Karte zum vergleichen hat. Kannst du sowas noch in digital und ordentlich machen?

**Comment by AdniLunA** [comment]
also von meinem jetzigen Netz? Wird gemacht :)
Soll ich die dann auch in dem Navi Ordner abspeichern? oder woanders
