### ISSUE TITLE
Sortierung der Liste

### ISSUE THREAD

**Issue by Abuturku** [Abuturku/Navi#2]
Auf Basis einer Usereingabe der Autobahnnummer
- entweder nach Kilometer der Ausfahrt
- oder Ausfahrten alphabetisch
- oder (Fall "0") Ausfahrten aller Autobahnen alphabetisch

**Comment by Abuturku** [comment]
Liste wird im Programmablauf sortiert.
Es fehlt das Übertragen in die Datei.

**Comment by DieAkuteSense** [comment]
Done :D

**Comment by DieAkuteSense** [comment]
Sollen die ganzen Blöcke geschrieben werden und dann das ganze in "autobahn.txt" umbenannt werden?

**Comment by Abuturku** [comment]
Wenn du nur die Orte in eine Liste sortiert haben willst, dann passt das so.
Ich dachte aber, dass ich die ganzen Arrays nochmal zu einem zusammenfüge und dieses Array in die Autobahn.txt schreibe. Dann müssen wir (wie du schon vorgeschlagen) die Liste nur sortieren, wenn man einen Eintrag hinzufügt. Quicksort ist übrigens auf eine bereits sortierte Liste mit der langsamste Algorithmus.

**Comment by DieAkuteSense** [comment]
Perfomancemäßig einfach mal testen ob es einen großen Unterschied macht? Könnte man machen wenn man eine Datei mit vielen Einträgen hat.
Wenn das sehr viel langsamer ist wäre es sinnvoller doch immer zu sortieren und nicht nur beim Hinzufügen eines neuen Eintrags

**Comment by AdniLunA** [comment]
problemchen:
- Option Autobahnnummer 0 nicht erklärt
- Eingabe Autobahnnummer 0 -> man kann wie immer 1/2 auswählen, danach wird programm direkt beendet
- einige der Autobahnnummern werden doppelt ausgegeben
- sollen die namen/autobahnkilometer der Ausfahrten so tabellarisch ausgegeben werden? mit tab realisiert? -> bei kurzen namen führt es dazu, dass die km bei sortierung nach alphabet aus der reihe tanzen

sind diese probleme bekannt?

**Comment by Abuturku** [comment]
Ich hab mal alles was du da oben stehen hast gefixt, denke ich (ist auch im Master).
Testet mal, ob ihr noch irgendwas findet.
Sollte aber soweit eigentlich fertig sein bezüglich der Sortierung und Ausgabe.
Wäre nur noch die Frage, wo wir die Funktion sort_list() einbauen.
